#!/bin/bash

case "$1" in
  "start")
    docker-compose up -d
  ;;

  "follow")
    docker-compose logs -f
  ;;

  "stop")
    docker-compose stop
  ;;

  "destroy")
    echo "This action will destroy all related containers as well as associated data."
    read -p "Are you sure? [y|N] " -n 1 -r; echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
      echo "Aborting mission... Close call!"
      exit 0
    fi
    docker-compose stop
    docker-compose rm -fv
    sudo rm -rf data/mysql data/web
esac
