#!/bin/bash
# /scripts/post-install.d/20-install-jetpack

set -e
shopt -s expand_aliases
alias wp="wp --path=$DOCUMENT_ROOT --allow-root"

echo "----> Post-Install: Jetpack Plugin."
if ! $(wp plugin is-installed jetpack); then
  wp plugin install jetpack
  wp plugin activate jetpack
fi
